version: '3.3'
services:
  nginxssl:
    image:
      weinginx:web
    ports:
      - 80:80
      - 443:443
    container_name: nginxssl
  nodeserver:
    image:
      weinginx:node
    ports:
      - 3000:3000
    container_name: nodeserver
  rtmpserver:
    image:
      weinginx:rtmp
    ports:
      - 2500:80
      - 8080:8080
      - 1935:1935
      - 1936:1936
    container_name: rtmpserver